wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.9
    start_time: 1645587821
    t:
      1:
      - 1
      2:
      - 1
      4: 3.9.9
      5: 0.12.10
      8:
      - 5
